### ISSUE TITLE
Package import issue

### ISSUE THREAD

**Issue by rupesx26** [Steveeeie/react-page-transition#5]
Hey, your pacakge is very cool ! trying to implementing in my project but getting stuck in while importing package from node_module 

error : "export 'default' (imported as 'PageTransition') was not found in '@steveeeie/react-page-transition'

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by Steveeeie** [comment]
Hi rupesx26,

Firstly, thanks for your kind words.

Sorry that you have had trouble importing the component. I recently refactored the code and changed it to use a named export instead of a default export but forgot to update the README. 

I should have also released it with a major version number to highlight the breaking change.

If you replace: 

```js
import PageTransition from '@steveeeie/react-page-transition';
```

with:

```js
import { PageTransition } from '@steveeeie/react-page-transition';
```

it should work.

Steve
